### ISSUE TITLE
Should not build-dep on golang-gocheck-dev

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/go-lib#2]
Golang-gocheck-dev seems an old, unmaintained version of golang-check.v1-dev. Both are available in Debian/Ubuntu/Deepin Archive.

**Comment by hualet** [comment]
@jouyouyun

**Comment by hosiet** [comment]
https://tracker.debian.org/news/844477

We no longer have `golang-gocheck-dev` in future releases of Debian.

**Comment by jouyouyun** [comment]
Fixed, see: https://cr.deepin.io/25134
