### ISSUE TITLE
Should not build-dep on golang-kingpin.v2-dev

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/go-lib#3]
There is golang-gopkg-alecthomas-kingpin.v2-dev, but no golang-kingpin.v2-dev.

**Comment by hualet** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
Fixed, see: https://cr.deepin.io/25106

**Comment by hosiet** [comment]
Pending till merged upstream.

**Comment by jouyouyun** [comment]
Has merged to master!
