### ISSUE TITLE
Migrate from golang-github-howeyc-fsnotify to golang-fsnotify

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/go-lib#4]
howeyc/fsnotify has been forked and actively maintained by fsnotify/fsnotify. Migration is recommended by upstream.

**Comment by hualet** [comment]
@snyh @jouyouyun

**Comment by jouyouyun** [comment]
@hosiet  fsnotify/fsnotify can not run on alpha architecture, so used howeyc/fsnotify.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
